---
id: "siteconfig.json"
"$schema": "http://json-schema.org/draft-04/schema"
title: Site config
description: Configuration of a single site
type: object
properties:
  name:
    type: string
  style:
    type: string
  favicon:
    type: string
  cta:
    type: object
  analytics:
    type: object
  opengraph:
    type: object
  collections:
    type: array

required: [name]
