---
"$schema": http://json-schema.org/draft-04/schema
id: schemata/siteconfig
title: Site config
description: Configuration of a single site
definitions:
  id:
    description: unique identifier of siteconfig
    example: 01234567-89ab-cdef-0123-456789abcdef
    format: uuid
    type:
    - string
type:
- object
properties:
  name:
    type: string
  style:
    type: string
  favicon:
    type: string
  cta:
    type: object
  analytics:
    type: object
  opengraph:
    type: object
  collections:
    type: array

required: [name]

